=== SergeyKorolenko/JavaST_2019/Task4XML/src/main/resources/data/gems.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.korolenko.by/gems"
        xmlns:tns="http://www.korolenko.by/gems"
        elementFormDefault="qualified">
    <element name="stone" type="tns:GemType" abstract="true"/>
    <element name="precious" type="tns:Precious" substitutionGroup="tns:stone"/>
    <element name="semiprecious" type="tns:Semiprecious"
             substitutionGroup="tns:stone"/>
    <element name="gems">
        <complexType>
            <sequence>
                <element ref="tns:stone" minOccurs="1" maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>
    <complexType name="GemType">
        <sequence>
            <element name="name" type="string"/>
            <element name="origin">
                <simpleType>
                    <restriction base="string">
                        <pattern value="[a-zA-Z]+"/>
                    </restriction>
                </simpleType>
            </element>
            <element name="visual_parameters" type="tns:VisualParameters"/>
            <element name="production_date" type="dateTime"/>
        </sequence>
        <attribute name="number" use="required">
            <simpleType>
                <restriction base="ID">
                    <pattern value="\w+"/>
                </restriction>
            </simpleType>
        </attribute>
    </complexType>
    <complexType name="Precious">
        <complexContent>
            <extension base="tns:GemType">
                <sequence>
                    <element name="carats" type="double"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>
    <complexType name="Semiprecious">
        <complexContent>
            <extension base="tns:GemType">
                <sequence>
                    <element name="weight">
                        <simpleType>
                            <restriction base="double">
                                <minInclusive value="0.01"/>
                            </restriction>
                        </simpleType>
                    </element>
                </sequence>
            </extension>
        </complexContent>
    </complexType>
    <complexType name="VisualParameters">
        <sequence>
            <element name="transparency">
                <simpleType>
                    <restriction base="int">
                        <minInclusive value="0"/>
                        <maxInclusive value="100"/>
                    </restriction>
                </simpleType>
            </element>
            <element name="cut_method" type="string"/>
            <element name="faces">
                <simpleType>
                    <restriction base="int">
                        <minInclusive value="4"/>
                        <maxInclusive value="15"/>
                    </restriction>
                </simpleType>
            </element>
        </sequence>
        <attribute name="color" use="optional" default="Transparent">
            <simpleType>
                <restriction base="string">
                    <enumeration value="Transparent"/>
                    <enumeration value="Red"/>
                    <enumeration value="Blue"/>
                    <enumeration value="Orange"/>
                    <enumeration value="Yellow"/>
                    <enumeration value="Pink"/>
                    <enumeration value="Gray"/>
                    <enumeration value="Green"/>
                    <enumeration value="Brown"/>
                </restriction>
            </simpleType>
        </attribute>
    </complexType>
</schema>

=== SergeyKorolenko/JavaST_2019/Task4XML/data/gems.xml
<?xml version="1.0" encoding="UTF-8"?>
<gems xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xmlns="http://www.korolenko.by/gems"
      xsi:schemaLocation="http://www.korolenko.by/gems gems.xsd">
    <precious number="num1">
        <name>Diamond</name>
        <origin>Africa</origin>
        <visual_parameters>
            <transparency>50</transparency>
            <cut_method>Rose</cut_method>
            <faces>15</faces>
        </visual_parameters>
        <production_date>2019-10-26T10:00:00</production_date>
        <carats>1</carats>
    </precious>
    <semiprecious number="num2">
        <name>Sapphire</name>
        <origin>Russia</origin>
        <visual_parameters color="Red">
            <transparency>24</transparency>
            <cut_method>Usher</cut_method>
            <faces>6</faces>
        </visual_parameters>
        <production_date>2019-10-29T09:04:00</production_date>
        <weight>0.5</weight>
    </semiprecious>
    <semiprecious number="num3">
        <name>Garnet</name>
        <origin>Belarus</origin>
        <visual_parameters color="Gray">
            <transparency>20</transparency>
            <cut_method>Table</cut_method>
            <faces>4</faces>
        </visual_parameters>
        <production_date>2019-03-24T18:00:00</production_date>
        <weight>2.5</weight>
    </semiprecious>
    <semiprecious number="num4">
        <name>Demantoid</name>
        <origin>German</origin>
        <visual_parameters color="Green">
            <transparency>10</transparency>
            <cut_method>Usher</cut_method>
            <faces>8</faces>
        </visual_parameters>
        <production_date>2019-06-05T09:25:00</production_date>
        <weight>1.2</weight>
    </semiprecious>
    <precious number="num5">
        <name>Amethyst</name>
        <origin>Belgium</origin>
        <visual_parameters color="Pink">
            <transparency>70</transparency>
            <cut_method>Rose</cut_method>
            <faces>7</faces>
        </visual_parameters>
        <production_date>2019-10-19T21:35:00</production_date>
        <carats>2</carats>
    </precious>
    <precious number="num6">
        <name>Beryl</name>
        <origin>Russia</origin>
        <visual_parameters color="Green">
            <transparency>100</transparency>
            <cut_method>Step</cut_method>
            <faces>11</faces>
        </visual_parameters>
        <production_date>2019-01-01T01:00:00</production_date>
        <carats>1.5</carats>
    </precious>
    <precious number="num7">
        <name>Apatite</name>
        <origin>China</origin>
        <visual_parameters color="Yellow">
            <transparency>18</transparency>
            <cut_method>Rose</cut_method>
            <faces>13</faces>
        </visual_parameters>
        <production_date>2019-12-31T23:00:00</production_date>
        <carats>4</carats>
    </precious>
    <precious number="num8">
        <name>Diamond</name>
        <origin>Japan</origin>
        <visual_parameters>
            <transparency>04</transparency>
            <cut_method>Table</cut_method>
            <faces>5</faces>
        </visual_parameters>
        <production_date>2019-05-26T14:00:00</production_date>
        <carats>2.5</carats>
    </precious>
    <semiprecious number="num9">
        <name>Sapphire</name>
        <origin>Russia</origin>
        <visual_parameters color="Orange">
            <transparency>56</transparency>
            <cut_method>Step</cut_method>
            <faces>9</faces>
        </visual_parameters>
        <production_date>2019-02-14T17:31:00</production_date>
        <weight>1.4</weight>
    </semiprecious>
    <precious number="num10">
        <name>Turquoise</name>
        <origin>Turkey</origin>
        <visual_parameters color="Blue">
            <transparency>80</transparency>
            <cut_method>Wedges</cut_method>
            <faces>15</faces>
        </visual_parameters>
        <production_date>2019-09-01T08:00:00</production_date>
        <carats>3</carats>
    </precious>
    <semiprecious number="num11">
        <name>Sapphire</name>
        <origin>Spain</origin>
        <visual_parameters color="Red">
            <transparency>93</transparency>
            <cut_method>Rose</cut_method>
            <faces>6</faces>
        </visual_parameters>
        <production_date>2019-08-28T09:00:00</production_date>
        <weight>0.4</weight>
    </semiprecious>
    <semiprecious number="num12">
        <name>Sapphire</name>
        <origin>Italy</origin>
        <visual_parameters color="Yellow">
            <transparency>14</transparency>
            <cut_method>Wedges</cut_method>
            <faces>10</faces>
        </visual_parameters>
        <production_date>2019-11-21T09:05:00</production_date>
        <weight>0.7</weight>
    </semiprecious>
    <precious number="num13">
        <name>Jet</name>
        <origin>France</origin>
        <visual_parameters color="Brown">
            <transparency>09</transparency>
            <cut_method>Rose</cut_method>
            <faces>12</faces>
        </visual_parameters>
        <production_date>2019-03-26T10:18:00</production_date>
        <carats>4.5</carats>
    </precious>
    <precious number="num14">
        <name>Diamond</name>
        <origin>Africa</origin>
        <visual_parameters>
            <transparency>78</transparency>
            <cut_method>Step</cut_method>
            <faces>8</faces>
        </visual_parameters>
        <production_date>2019-12-02T19:00:00</production_date>
        <carats>0.5</carats>
    </precious>
    <precious number="num15">
        <name>Sapphire</name>
        <origin>USA</origin>
        <visual_parameters color="Brown">
            <transparency>45</transparency>
            <cut_method>Rose</cut_method>
            <faces>11</faces>
        </visual_parameters>
        <production_date>2019-10-25T11:00:00</production_date>
        <carats>3.5</carats>
    </precious>
    <semiprecious number="num16">
        <name>Sapphire</name>
        <origin>Russia</origin>
        <visual_parameters color="Red">
            <transparency>36</transparency>
            <cut_method>Step</cut_method>
            <faces>7</faces>
        </visual_parameters>
        <production_date>2019-07-05T17:56:00</production_date>
        <weight>0.9</weight>
    </semiprecious>
</gems>

=== SergeyKorolenko/JavaST_2019/Task4XML/src/main/resources/data/gems.xml
<?xml version="1.0" encoding="UTF-8"?>
<gems xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xmlns="http://www.korolenko.by/gems"
      xsi:schemaLocation="http://www.korolenko.by/gems gems.xsd">
    <precious number="num1">
        <name>Diamond</name>
        <origin>Africa</origin>
        <visual_parameters>
            <transparency>50</transparency>
            <cut_method>Rose</cut_method>
            <faces>15</faces>
        </visual_parameters>
        <production_date>2019-10-26T10:00:00</production_date>
        <carats>1</carats>
    </precious>
    <semiprecious number="num2">
        <name>Sapphire</name>
        <origin>Russia</origin>
        <visual_parameters color="Red">
            <transparency>50</transparency>
            <cut_method>Rose</cut_method>
            <faces>6</faces>
        </visual_parameters>
        <production_date>2019-10-29T09:04:00</production_date>
        <weight>0.5</weight>
    </semiprecious>
</gems>
